---

docker_log_driver: "json-file"
docker_log_max_size: "100m"
docker_log_max_file: "3"

docker_ipv6: false

docker_data_root: /var/lib/docker

docker_metrics_addr: "0.0.0.0:9323"
docker_experimental: false
